name: Nodejs ci

on:
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        
        permissions:
            contents: write
            pull-requests: write
            repository-projects: write
            issues: write

        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '14'

            - name: npm install dependencies
              run: npm install

            - name: lint code
              id: lint
              continue-on-error: true
              run: npm run eslint

            - name: run build
              run: npm run build --if-present

            - name: test code
              id: test
              continue-on-error: true
              run: npm run test:unit

            - name: create issue if test fails
              if: ${{ steps.test.outcome == 'failure' }}
              uses: actions/github-script@v7
              with:
                script: |
                    await github.rest.issues.create({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      title: 'Build failed',
                      body: 'The build for this PR has failed. Please check the build logs for more details.',
                      labels: ['build:failed'],
                      assignees: [context.actor],
                    });
            
            - name: build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: build-artifacts
                  path: dist
            
            - name: close opened issues
              uses: actions/github-script@v7
              with:
                script: |
                    const repos = await github.rest.issues.listForRepo({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      labels: ['build:failed'],
                    });
                    console.log('steps.test.outcome',${{steps.test.outcome}});

                    for (const repo of repos.data) {
                      if (repo.state === 'open' && steps.test.outcome !== 'failure')
                      await github.rest.issues.update({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: repo.number,
                        state: 'closed',
                      });
                    }
                   
              