name: Nodejs ci

on:
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        
        permissions:
            contents: write
            pull-requests: write
            repository-projects: write
            issues: write

        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: npm install dependencies
              continue-on-error: true
              id: install-node
              run: npm install

            - run: pwd && ls ./ -a
            
            - name: Report error if install failed
              uses: ./.github/actions/report
              with:
                outcome: ${{steps.install-node.outcome}}
                label: 'install-failed'
                title: 'install failed'


            - name: lint code
              id: lint
              continue-on-error: true
              run: npm run eslint

            - name: Report error if lint failed
              uses: ./.github/actions/report
              with:
                outcome: ${{steps.lint.outcome}}
                label: 'lint:failed'
                title: 'lint failed'

            - name: run build
              id: build
              run: npm run build --if-present

            - name: Report error if build failed
              uses: ./.github/actions/report
              with:
                outcome: ${{steps.lint.outcome}}
                label: 'build:failed'
                title: 'build failed'

            - name: test code
              id: test
              continue-on-error: true
              run: npm run test:unit

            - name: Report error if build failed
              uses:  ./.github/actions/report
              with:
                outcome: ${{steps.lint.outcome}}
                label: 'build:failed'
                title: 'build failed'

            - name: build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: build-artifacts
                  path: dist
            
           
                   
              